ServiceHost/Areas/Admin/Pages/Account/Role/Create.cshtml.cs
using _01_Framework.Infrastrue;
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Admin.Pages.Account.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole command;

        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposer;
        public List<SelectListItem> Permissions = new List<SelectListItem>();
        public CreateModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposer)
        {
            _roleApplication = roleApplication;
            _exposer = exposer;
        }

        public void OnGet()
        {
            foreach (var exposer in _exposer)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key, value) in exposedPermissions)
                {
                    var group = new SelectListGroup { Name = key };
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group
                        };

                        Permissions.Add(item);

                    }
                }
            }
        }
        public IActionResult OnPost(CreateRole command)
        {
            var resualt = _roleApplication.Create(command);
             
            return RedirectToPage("/Index");
        }

    }
}

ServiceHost/Areas/Admin/Pages/Inventory/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StoreManager.Application.Contract.Inventory;
using StoreManager.Application.Contract.Product;
using System.Collections.Generic;

namespace ServiceHost.Areas.Admin.Pages.Inventor
{
    public class IndexModel : PageModel
    {

        private readonly INventoryApplication _inventoryApplication;

        private readonly IProductApplication _productApplication;

        public IndexModel(INventoryApplication inventoryApplication, IProductApplication productApplication)
        {
            _inventoryApplication = inventoryApplication;
            _productApplication = productApplication;
        }

        public List<InventoryViewModel> inventories { get; set; }


        public void OnGet(SearchInventory search)
        {
            inventories = _inventoryApplication.Search(search);
        }


        public PartialViewResult OnGetCreate()
        {
            var model = new CreateInventory()
            {
                products = _productApplication.GetSelectList()
            };
            return Partial("./Create", model);
        }

        public IActionResult OnPostCreate(CreateInventory command)
        {
            var resualt = _inventoryApplication.Create(command);

            return RedirectToPage("Index"); ;
        }


        public PartialViewResult OnGetEdit(long id)
        {
            var inventoryModel = _inventoryApplication.GetDetails(id);
            return Partial("./Edit", inventoryModel);
        }

        public IActionResult OnPostEdit(EditInventory command)
        {
            var resualt = _inventoryApplication.Edit(command);

            return RedirectToPage("Index");
        }




        public PartialViewResult OnGetIncrease(long id)
        {
            var Increase = new IncreaseInventory()
            {
                InvantoryId = id,
                CurrentCount = _inventoryApplication.CurrentCount(id)
            };
            return Partial("./Increase", Increase);
        }

        public IActionResult OnPostIncrease(IncreaseInventory command)
        {
            var resualt = _inventoryApplication.Increase(command);
            return RedirectToPage("Index");
        }



        public PartialViewResult OnGetDecrease(long id)
        {
            var Decreas = new DecreaseInventory()
            {
                InvantoryId = id,
                CurrentCount = _inventoryApplication.CurrentCount(id)
            };
            return Partial("./Decrease", Decreas);
        }

        public IActionResult OnPostDecrease(DecreaseInventory command)
        {
            var resualt = _inventoryApplication.Decrease(command);
            return RedirectToPage("Index");
        }


        public IActionResult OnGetInventoryLog(long id)
        {
            var Model = _inventoryApplication.ShowInventoryLog(id);
            return Partial("./InventoryLog", Model);
        }

    }
}

ServiceHost/Areas/Admin/Pages/Inventory/Create.cshtml
@model StoreManager.Application.Contract.Inventory.CreateInventory

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد محصول جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Price" class="control-label">قیمت</label>
                    <input type="text" class="form-control" asp-for="Price" onchange="makeSlug('Name', 'Slug')">
                    <ul class="parsley-errors-list filled" id="parsley-id-32">
                        <li class="parsley-required">
                            <span asp-validation-for="Price"></span>
                        </li>
                    </ul>
                </div>
            </div>
        
        </div>
   
        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">

                    <select asp-for="ProductId" class="form-select form-control" asp-items='new SelectList(Model.products, "Id", "Name")'>
                        <option value="0">گروه محصولی ...</option>
                    </select>
                    <ul class="parsley-errors-list filled" id="parsley-id-32">
                        <li class="parsley-required">
                            <span asp-validation-for="ProductId"></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Inventory/Decrease.cshtml
@model StoreManager.Application.Contract.Inventory.DecreaseInventory


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">تعداد موجودی فعلی در انبار (@Model.CurrentCount)</h4>
</div>
<form asp-page="./Index" asp-page-handler="Decrease"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Count" class="control-label">تعداد خروج از انبار</label>
                    <input type="number" class="form-control" asp-for="Count">
                    <ul class="parsley-errors-list filled" id="parsley-id-32">
                        <li class="parsley-required">
                            <span asp-validation-for="Count"></span>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Description" class="control-label">توضیحات</label>
                    <br />
                    <textarea asp-for="Description">

                    </textarea>
                    <ul class="parsley-errors-list filled" id="parsley-id-32">
                        <li class="parsley-required">
                            <span asp-validation-for="Description"></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="InvantoryId" value="@Model.InvantoryId" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">کم کردن</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Inventory/Edit.cshtml
@model StoreManager.Application.Contract.Inventory.EditInventory

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش انبار محصول (@Model.Product)</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Price" class="control-label">قیمت</label>
                    <input type="text" class="form-control" asp-for="Price" onchange="makeSlug('Name', 'Slug')">
                    <ul class="parsley-errors-list filled" id="parsley-id-32">
                        <li class="parsley-required">
                            <span asp-validation-for="Price"></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
      
        <input type="hidden" class="form-control" asp-for="id" value="@Model.id">

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Inventory/Increase.cshtml
@model StoreManager.Application.Contract.Inventory.IncreaseInventory


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">تعداد موجودی فعلی در انبار (@Model.CurrentCount)</h4>
</div>
<form asp-page="./Index" asp-page-handler="Increase"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Count" class="control-label">تعداد ورود به انبار</label>
                    <input type="number" class="form-control" asp-for="Count">
                    <ul class="parsley-errors-list filled" id="parsley-id-32">
                        <li class="parsley-required">
                            <span asp-validation-for="Count"></span>
                        </li>
                    </ul>
                </div>
            </div>   
            
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Description" class="control-label">توضیحات</label> 
                    <br />
                    <textarea asp-for="Description">

                    </textarea>
                    <ul class="parsley-errors-list filled" id="parsley-id-32">
                        <li class="parsley-required">
                            <span asp-validation-for="Description"></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="InvantoryId" value="@Model.InvantoryId" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">اضافه کردن</button>
    </div>
</form>

ServiceHost/Areas/Admin/Pages/Inventory/Index.cshtml
@page
@model ServiceHost.Areas.Admin.Pages.Inventor.IndexModel
@{
    ViewData["AdminTitle"] = "انبار داری";
    Layout = "_AdminLayout";
}
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal Tittle</h4>
            </div>
            <div class="modal-body">
                Body goes here...
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
                <button class="btn btn-success" type="button">Save changes</button>
            </div>
        </div>
    </div>
</div>
<!-- modal -->


<div class="col-lg-12">
    <section class="panel">
        <div class="panel-body">
            <a href="#showmodal=@Url.Page("./Index", "Create")" class="btn btn-white btn-icon-text my-2 ml-2">
                  ایجاد انبار<i class="fe fe-download mr-2"></i>
            </a>
        </div>
    </section>
</div>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
            </header>
            <div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
                <div class="row"><div class="col-sm-6"><div id="sample_1_length" class="dataTables_length"><label><select size="1" name="sample_1_length" aria-controls="sample_1" class="form-control"><option value="10" selected="selected">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> records per page</label></div></div><div class="col-sm-6"><div class="dataTables_filter" id="sample_1_filter"><label>Search: <input type="text" aria-controls="sample_1" class="form-control"></label></div></div></div><table class="table table-striped border-top dataTable" id="sample_1" aria-describedby="sample_1_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample_1" rowspan="1" colspan="1" style="width: 310px;" aria-label="id: activate to sort column ascending">#</th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample_1" rowspan="1" colspan="1" style="width: 310px;" aria-label="picture: activate to sort column ascending">محصول</th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample_1" rowspan="1" colspan="1" style="width: 113px;" aria-label="name: activate to sort column ascending">قیمت</th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample_1" rowspan="1" colspan="1" style="width: 169px;" aria-label="code: activate to sort column ascending">وضعیت</th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="sample_1" rowspan="1" colspan="1" style="width: 179px;" aria-label=": activate to sort column ascending">عملیات</th>

                        </tr>
                    </thead>

                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                        @foreach (var inventory in Model.inventories)
                        {
                            <tr role="row" class="odd">
                                <td style="padding-top:18px" class="id">@inventory.Id</td>

                                <td style="padding-top:18px"  class="sorting_1">@inventory.Product</td>

                                <td style="padding-top:18px" >@inventory.Price</td>




                                <td class="date">
                                    @if (!inventory.IsInStock)
                                    {
                                      <i style="color:red;font-size:xx-large" class="icon-remove"></i>
                                    }
                                    else
                                    {                                 
                                        <i style="color:green;font-size:xx-large" class="icon-ok-sign"></i>
                                    }
                                </td>

                                <td>
                                    <div class="btn-group">
                                        <button data-toggle="dropdown" class="btn btn-primary dropdown-toggle btn-sm" type="button">عملیات ها<span class="caret"></span></button>
                                        <ul role="menu" class="dropdown-menu">
                                            <li>
                                                <a href="#showmodal=@Url.Page("./Index", "Edit",new{id=inventory.Id})" class="btn btn-info">ویرایش<i class="icon-refresh"></i></a>
                                            </li>
                                            <li style="margin-top:inherit">
                                                <a href="#showmodal=@Url.Page("./Index", "Increase",new{id=inventory.Id})" class="btn btn-success"><i class="icon-long-arrow-up"></i>افزایش موجودی</a>
                                            </li>
                                            <li style="margin-top:inherit">
                                                <a href="#showmodal=@Url.Page("./Index", "Decrease",new{id=inventory.Id})" class="btn btn-danger"><i class="icon-long-arrow-down"></i>کاهش موجودی</a>
                                            </li>
                                            <li style="margin-top:inherit">
                                                <a href="#showmodal=@Url.Page("./Index", "InventoryLog",new{id=inventory.Id})" class="btn btn-warning"><i class="icon-spinner"></i>گردش انبار</a>
                                            </li>
                                        </ul>
                                    </div>


                                </td>
                            </tr>

                        }

                    </tbody>
                </table><div class="row"><div class="col-sm-6"><div class="dataTables_info" id="sample_1_info">Showing 1 to 10 of 25 entries</div></div><div class="col-sm-6"><div class="dataTables_paginate paging_bootstrap pagination"><ul><li class="prev disabled"><a href="#">← Prev</a></li><li class="active"><a href="#">1</a></li><li><a href="#">2</a></li><li><a href="#">3</a></li><li class="next"><a href="#">Next → </a></li></ul></div></div></div>
            </div>
        </section>
    </div>
</div>
<!-- page end-->

ServiceHost/Areas/Admin/Pages/Inventory/InventoryLog.cshtml
@model List<StoreManager.Application.Contract.Inventory.OprationViewModel>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">
        اطلاعات انبار
    </h4>
</div>

<form asp-page="./Index" asp-page-handler="Increase"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">


        <div class="col-lg-12">
            <div class="card custom-card overflow-hidden">
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                            <div class="row">
                                <div class="col-sm-12 col-md-6">
                                    <div class="dataTables_length" id="example1_length">
                                        <label>
                                            <select name="example1_length" aria-controls="example1" class="custom-select custom-select-sm form-control form-control-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> items/page
                                        </label>
                                    </div>
                                </div>

                            </div><div class="row">
                                <div class="col-sm-12">
                                    <table class="table dataTable no-footer" id="example1" role="grid" aria-describedby="example1_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="wd-20p sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width: 140.733px;" aria-sort="ascending" aria-label="Name: activate to sort column descending">
                                                    #
                                                </th>
                                                <th class="wd-25p sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width: 186.083px;" aria-label="Position: activate to sort column ascending">تعداد</th>
                                                <th class="wd-20p sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width: 140.733px;" aria-label="Office: activate to sort column ascending">تاریخ</th>
                                                <th class="wd-15p sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width: 95.3833px;" aria-label="Age: activate to sort column ascending">موجودی فعلی</th>
                                                <th class="wd-20p sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width: 140.733px;" aria-label="Salary: activate to sort column ascending">عملگر</th>
                                                <th class="wd-20p sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width: 140.733px;" aria-label="Salary: activate to sort column ascending">توضیحات</th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr role="row" class="text-white" style="@(item.ServiceInput ? "background-color: #78b56f" : "background-color: #F66;");color:white">
                                                    <td class="sorting_1">@item.id</td>
                                                    <td>@item.Count</td>
                                                    <td>@item.CreationDate</td>
                                                    <td>@item.CurrentCount</td>
                                                    <td>@(item.Character == 1 ? "مدیر سیستم" : "")</td>
                                                    <td>@(string.IsNullOrWhiteSpace(item.Description) ? ". . . . . .": item.Description)</td>
                                                </tr>
                                            }


                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">افزایش</button>
    </div>
</form>